services:
  postgres:
    image: postgres:14.8-alpine3.18 
    restart: unless-stopped
    environment: 
      POSTGRES_DB: "ys-db"
      POSTGRES_USER: "ys-user"
      POSTGRES_PASSWORD: "qwerty"
      # PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      # - ./db-data/:/var/lib/postgresql/data/
      - ./migrations:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret

      # Для подключения к pgadmin:
      # Hostname/address: postgres
      # Maintenance Database: ys-db 
      # USER: ys-user 
      # PASSWORD: qwerty
volumes:
  db-data: